# Generated by Django 6.1 on 2026-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='image',
            field=models.ImageField(blank=True, upload_to='devices/%Y/%m/'),
        ),
    ]
