# Generated by Django 6.1 on 2026-09-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='usuario',
        ),
    ]
