# Generated by Django 6.1 on 2026-09-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('INFO', 'Informativa'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='WARNING', max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('ACKNOWLEDGED', 'Reconocida'), ('RESOLVED', 'Resuelta')], default='OPEN', max_length=15),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Finalizada')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='type',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventiva'), ('CORRECTIVE', 'Correctiva')], max_length=15),
        ),
    ]
